### ISSUE TITLE
Versionierung

### ISSUE THREAD

**Issue by Hummel83** [laroche/trading-gmbh#1]
Es wär sinnvoll eine Versionierung am Anfang der Website(pdf) zu machen. Wo jeder User sehen kann von wann das Dokument ist. Nicht jeder wird den Push feed lesen.

**Comment by laroche** [comment]
Ein Erstellungsdatum steht bisher im pdf-Header mit dabei, ich hab einfach noch das Datum mit in
die pdf-Ausgabe aufgenommen.
