### ISSUE TITLE
Ist eine Stiftung auch eine Option?

### ISSUE THREAD

**Issue by bm765** [laroche/trading-gmbh#5]
Hi,

danke für das Aufsetzen und Pflegen dieses Projekts!

Auf [Welt der Finanzen - Financial Must-Haves - David Kasper@KÖBERPartner GmbH Steuerberatungsgesellschaft](https://youtu.be/Uv5wzkCb0fY?t=17941) gibt es übrigens auch ein Video zu dem Thema - dort eher mit dem Fokus `Stiftung gründen`.

**Comment by laroche** [comment]
Hallo,

David Kasper von Köber macht wirklich gute Informationsvideos sowohl zu GmbHs wie auch Stiftungen.
Mein aktuelles Dokument enthält die entsprechenden Links dazu, daher schliesse ich hier den "Issue".

Viele Grüße aus Stuttgart,

Florian La Roche
